### ISSUE TITLE
Can't get the value of RadioButton selection

### ISSUE THREAD

**Issue by VulcanRav** [peterbrittain/asciimatics#101]
Hello, I'm trying to use a print_at method to check the data of my frame.

This is the code:

```
def add_coin_menu(screen):
    top_layout = Layout([1], fill_frame=False)
    frame = Frame(screen, 18, 70, has_border=False)
    frame.add_layout(top_layout)
    my_list = [("CHOICE ONE", 0), ("CHOICE TWO", 1), ("CHOICE THREE", 2)]
    radio_exchange = RadioButtons(my_list, name="list_choice")
    text = Text("CHOOSE YOUR CHOICE")
    text.disabled
    top_layout.add_widget(text)
    top_layout.add_widget(radio_exchange)
    frame.fix()
    scenes = [
        Scene([frame], -1, name="Add Coin Frame")
    ]
    def global_shortcuts(event):
        if isinstance(event, KeyboardEvent):
            c = event.key_code
            # Stop on ctrl+q or ctrl+x
            if c in (17, 24):
                screen.print_at("hello world", 0,0)
    
    screen.play(scenes, unhandled_input=global_shortcuts)


Screen.wrapper(add_coin_menu)
```
When I call the print_at method tho, the frame.data dictionary seems empty both for the box and the RadioButton menu.

Another question, why there's no widget to create simple text without it needing for user input? I tried to circumvent the issue by disabling the text.widget, but calling the .disabled method does nothing on this widget.

I am aware that my issues might be related to some lack of understanding of asciimatics on my side..

**Comment by peterbrittain** [comment]
I'm assuming that you just print the value instead of "hello world" in your sample code above.  If so, the short answers (with links to longer ones) are:

- You need to set `disabled` to `True` (http://asciimatics.readthedocs.io/en/latest/widgets.html#disabling-widgets)
- You need to call `save()` before `data` is valid (as per http://asciimatics.readthedocs.io/en/latest/widgets.html#getting-values).

More generally, I don't know what you mean by no "simple text" widget.  You have 2 options - the `Label` and disabled `Text` widgets.

**Comment by VulcanRav** [comment]
Yeah, I had frame.data or radio_exchange.value instead of Hello World (I used it to check if I was printing anything).

What do I have to call save on? The frame?

Thank you peter :)

**Comment by peterbrittain** [comment]
Yup - on the frame.

**Comment by peterbrittain** [comment]
And you're welcome.
