### ISSUE TITLE
Misc. Feature requests - Label alignment and Divider overrides

### ISSUE THREAD

**Issue by robinsiebler** [peterbrittain/asciimatics#103]
Maybe I'm just trying to do something strange, but I don't see any way to align controls - for instance, I want to display a label, but I want it to be centered or perhaps just offset. Also, it would be nice if I could specify how many chars long a divider is and what character is used for the divider.

Also, I have a group of controls that I want to draw a border around. I can't figure out how to do that. The only thing that seems to have a border property is a Frame. Can I have a Frame inside a Frame?

**Comment by peterbrittain** [comment]
Exact placement of widgets is exactly what I'm trying to avoid.  You can align groups of widgets vertically or horizontally, but you would need to recalculate exact placement each time the screen resizes if I allowed exact positioning.  I didn't want people dealing with that sort of crud, which is why you can only specify relative placement.

Taking more specific requests in turn...

- It's possible to define a length for a divider implicitly by specifying the width of the column it resides in, but I can see that might not fix all cases.
- Assuming you're happy to live with existing column logic, it's relatively easy to add a basic alignment (left, centre, right) option to Labels.  Would that help?
- A Divider character override is also possible.  I'll see what I can do there.
- There is no group box widget in asciimatics at the moment.  This will be hard to add; an embedded Frame won't work due to input logic and whatever gets implemented will further complicate the already slightly hairy widget placement logic.

**Comment by robinsiebler** [comment]
Thanks for your speedy response! I like your module and how well documented it is! Thanks for all your hard work!

In reply to your answers:

1. I understand what you are saying about the widget placement.
2. I understand what you are saying about divider. My only issue was with having the contents of 1 layout appear *right* next to the contents of another layout. I looked for a way to draw a vertical divider, but couldn't find one. I guess my solution to the issue can be to add a narrow layout that is empty as a spacer.
3. An alignment option for labels would be quite useful!
4. Thank you for that as well.
5. It was mostly a cosmetic issue. I will play with the custom colors option and see if I can solve the problem that way.

**Comment by peterbrittain** [comment]
Thanks.  It's always nice to know that your work is appreciated!

Let's try to wrap this up, then...  I reckon this issue becomes:

1. Please add an alignment option to Labels.
2. Please add an override character to Dividers.
3. Please provide a sensible way to visibly group a set of related widgets.

This last one is a lot more complex, so I'm going to spin that out into a separate issue (and re-purpose this issue to be just the first 2 items).

**Comment by peterbrittain** [comment]
Just polished off these two additions too...  See https://github.com/peterbrittain/asciimatics/commit/2d9c7feaf7bc075bba6eff024bdf68b12b3e117d
