### ISSUE TITLE
Provide a way to disable a group of widgets

### ISSUE THREAD

**Issue by garfieldnate** [peterbrittain/asciimatics#117]
I was trying to disable several widgets grouped in a frame by setting the frame's `disabled` field to True, but this didn't work. I think that is unintuitive. Setting `disabled` on a widget/layout should disable all of the children.

**Comment by peterbrittain** [comment]
I think you're confusing Frames, Layouts and Widgets.  There is no disabled property on Frames or Layouts, and no nesting of Widgets, so you can't disable a group of Widgets in this way.  

While I can see that it may be useful to disable a group of Widgets, I think that using the Frame to do  this is wrong.  Layouts might be plausible, but they are purely for typesetting rather than creating logical connections between Widgets.  However, https://github.com/peterbrittain/asciimatics/issues/104 would create a widget that ties together a set of related Widgets and so it would make sense for this to support this feature.  I've therefore rolled this into the other issue.

**Comment by peterbrittain** [comment]
As discussed, reopening this one as I don't expect to supply a separate container widget fornow.

**Comment by peterbrittain** [comment]
So...  Would a method to disable a Layout, or column in a Layout work for you?

**Comment by garfieldnate** [comment]
My current (incorrect) code sets the frame's `disable` attribute to `True`. If it's possible for me to simply put everything inside of the frame inside of a column layout and then disable the column, then it would work fine as-is.

**Comment by garfieldnate** [comment]
🎉 Thanks! Can't wait to use it!
