### ISSUE TITLE
Variable color for cell in MultiColumnListBox

### ISSUE THREAD

**Issue by chrisgeru** [peterbrittain/asciimatics#126]
Considering a MultiColumnListBox like this:

|Process | Status | Memory|
|-----------|-----------|-----------|
|Celery| Running | 200mb|
|supervisord|Not Running| -- |

How can I put "Running" in Green color and "Not Running" in red color?

I have tried inject the color code in text ('\x1b[32mRunning\x1b[0m') but did not work.

Any help?

**Comment by peterbrittain** [comment]
OK - I understand the use case and can see why you want to override the standard palette here.  

As you've discovered, there is no support for this right now, though...  In the current code, you'd need to override the `update()` method on `MultiColumnListBox` and re-implement it with your custom formatting.  Yuck!

Sounds like what's needed is some form of optional formatter callback that allows you to overrule the palette, or maybe some way to tag a part of a widget with a custom style - effectively extending the existing `custom` property to handle sub-sections of the widget.  I suspect that the latter is just a minefield - e.g. needing to allow for tagging of rows, columns, individual cells, etc.

There's also the question of how this should fit in with other widgets - e.g. syntax highlighting for text editing maybe?  I'll think about that case too and see whether there is any overlap here.

**Comment by chrisgeru** [comment]
Thanks for response. I was thinking in some simpler workaround: escape the color codes in text (like the -e option in echo command), but I really do not know if this is a simple implement in code.

I'll try to look the `update()` method - thanks for pointing.

**Comment by peterbrittain** [comment]
Yeah - I thought about that too.  Escape codes will be tricky for 3 reasons.

1. I'm using the curses APIs on Linux, which escapes any attempts to do this (as you've already seen).
2. There is no single set of codes that you can use on all Terminals - though ansi codes are pretty good these days.
3. They don't work at all on Windows - and so need a new translation layer (e.g. colorama).  

That's why I devised an alternative syntax for inline colours inside Renderers.  I wondered about supporting that here, but it doesn't work with the widget layout logic (which truncates any widget text to a required length).

My current gut feel is to go for the callback solution.  This could pass in the details of everything it's about to printed for a cell and allow the callback to make the final screen update.  This would allow both simple cell replacement colours that you need, but could also provide a template for more complex cases like the language syntax colouring for the TextBox.

It will be a while before I get round to this, so I'm open to other suggestions from the community in the meantime...

**Comment by peterbrittain** [comment]
I've started experimenting with this issue.  This branch (https://github.com/peterbrittain/asciimatics/tree/widget_formatter) contains a prototype interface for passing your own formatter into a Widget.

The formatter will be called with a context and then the paramters that should be passed on to `print_at` if you don't want to do anything special.  Details are here: https://github.com/peterbrittain/asciimatics/blob/410ed2f88fd900345c125cb33c0b0e8ecef8ce21/asciimatics/widgets.py#L1354-L1366

In theory you can pass your own formatter function into the constructor for your `MultiColumnLitBox` and then put something in there to spot when you're updating column 1 (i.e. the second column) and the text is "Not Running" then use a different colour of your choice.

I'm not sure whether I like this API, so some feedback would be appreciated...

**Comment by lwm** [comment]
Not familiar with the code and all that .. however, here goes one point ...

> or maybe some way to tag a part of a widget with a custom style - effectively extending the existing custom property to handle sub-sections of the widget. I suspect that the latter is just a minefield - e.g. needing to allow for tagging of rows, columns, individual cells, etc.

Feels like that should be documented somewhere.

Passing in the `_call_formatter` function seems fine for this widget but have you come up with some idea for configuring the pallete for other widgets? It seems like this `_call_formatter` style would be clumsy given that you'd have to write a function body for each widget when you just want to se a single color. Maybe that isn't relevant right now.

Looks good to me.

Bump @chrisgeru - any feedback?

**Comment by peterbrittain** [comment]
Sure - any support for this feature would be added to the documentation.  Don't all projects do that?  :-)

The thing I'm trying to do here is create a natural way to override any element of any widget.  This API effectively hooks the print_at calls, passing in a widget-specific context for every call.  As such, I think it is something that can be added to every widget fairly trivially - e.g. context for a TextBox could be the line you're printing, or a selection might be the option value of the item to be printed, etc.

However, I'm not convinced the context is very neat and probably still not enough if I wanted to allow people to do syntax colouring for a TextBox, for example.

**Comment by peterbrittain** [comment]
Am beginning to think that some new style of text string would be better...  

- It's relatively easy to add in colour attributes using `paint` instead of `print_at` as long as the app provides a colour map in addition to the text.  
- It's not very hard to make the List widgets recognize a new class that consists of a text string and a colour map for that string, and use `paint` to draw it.
- It's quite easy to push that new class instead of a string for this use case.

I still need to figure out how I would then use this for a the text entry in widgets like `TextBox`.  I suspect that it needs some parser to generate the colour map dynamically, which begins to sound like another variant of #131.

**Comment by peterbrittain** [comment]
In fact, the use of the parser is probably enough and arguably easier as you still can pass unicode strings everywhere.  In this implementation, you would just need to pass suitably encoded colour codings inline in the strings, which is what people are used to doing anyway...  I think I'mconvinced at this point.

**Comment by peterbrittain** [comment]
Got to the point where I've started prototyping.  Latest code (which only handles TextBoxes for now) is in https://github.com/peterbrittain/asciimatics/tree/colour_parsing

**Comment by peterbrittain** [comment]
I'll leave this open for now but main development is now covered in #131.  See that issue for latest updates.
