### ISSUE TITLE
Terminal's own foreground/background colours?

### ISSUE THREAD

**Issue by deanmaniatis** [peterbrittain/asciimatics#128]
Is it possible to omit foreground/background on a Screen and use the terminal's default colorscheme?

**Comment by peterbrittain** [comment]
Not sure what you're asking for here...  Are you talking about when the Screen initializes, when you're printing text (e.g. using `print_at`), or something like that?  Can you please provide a little more detail?

**Comment by deanmaniatis** [comment]
Hi,
I simply want to create some text output with print_at without asciimatics
default fg/bg colors.

Dean

**Comment by deanmaniatis** [comment]
Isn't possible not to configure any colours and simply have it pick up the colour-scheme from the terminal, e.g. solarized. For example when you are on the REPL and you use print it doesn't force any background/foreground colours on the text.

**Comment by peterbrittain** [comment]
Sorry, but that's not supported.  There is no standard for finding out what the current colours are in all terminals.  See https://stackoverflow.com/questions/28096697/how-to-get-current-terminal-color-pair-in-bash.

The way that asciimatics takes full control of the screen means it can't use print (and so just inherit the current colours from the running terminal).  The closest you could get is #46 (when implemented) as already mentioned.

**Comment by pawamoy** [comment]
I think what @deanmaniatis wanted was to be able to use something like `Screen.COLOUR_DEFAULT`, instead of forcing it to `Screen.COLOUR_BLACK`. Maybe see [`curses.use_default_colors`](https://docs.python.org/3/library/curses.html#curses.use_default_colors).

**Comment by peterbrittain** [comment]
Interesting function...  Just had a look and that's a simple wrapper to the ncurses function of the same name, which explicitly redefines a color palette [0] to be the "default colour scheme", which may be hard-coded to black and white if ncurses cannot figure it out.
This means that (a) it's still not a feature that you can rely on in many environments and (b) it's no good for asciimatics, which uses the terminfo DB directly rather than the ncurses functions built on top of it.
