### ISSUE TITLE
Issue on Python 3.6

### ISSUE THREAD

**Issue by tonybaloney** [peterbrittain/asciimatics#129]
Code works perfectly on Python 2.7, but in Python 3.6 crashes the first time Screen.refresh() is called.

```
Traceback (most recent call last):
  File "/Users/anthonyshaw/repo/retox-2/retox/__main__.py", line 66, in main
    screen.refresh()
  File "/Users/anthonyshaw/repo/retox-2/src/asciimatics/asciimatics/screen.py", line 2129, in refresh
    super(_CursesScreen, self).refresh()
  File "/Users/anthonyshaw/repo/retox-2/src/asciimatics/asciimatics/screen.py", line 1216, in refresh
    self._change_colours(new_cell[1], new_cell[2], new_cell[3])
  File "/Users/anthonyshaw/repo/retox-2/src/asciimatics/asciimatics/screen.py", line 2225, in _change_colours
    self._safe_write(self._a_normal)
  File "/Users/anthonyshaw/repo/retox-2/src/asciimatics/asciimatics/screen.py", line 2085, in _safe_write
    sys.stdout.write(msg)
  File "/Users/anthonyshaw/repo/retox-2/bin/../lib/python3.6/codecs.py", line 377, in write
    self.stream.write(data)
  File "/Users/anthonyshaw/repo/retox-2/bin/../lib/python3.6/codecs.py", line 376, in write
    data, consumed = self.encode(object, self.errors)
TypeError: utf_8_encode() argument 1 must be str, not bytes
```

Any help/tips on debugging would be appreciated.

**Comment by peterbrittain** [comment]
Hmmm...  The forms demo works fine for me on my python3.6 installation on CentOS, so it must be something about your environment or your application...

Looks like you're running a curses system.  The code is trying to reset the screen colours using a string that it has read from the terminfo database.  This text is explicitly read and decoded here: https://github.com/peterbrittain/asciimatics/blob/a2eb56e5a69a0295e0b0d00d7172976bf0f39dda/asciimatics/screen.py#L2034

It's therefore surprising that this is deemed to be a byte string rather than unicode string because it should have been completely decoded on initialisation.  I'm guessing that there is something going wrong at initialisation.  Can you please confirm what text is being returned to asciimatics?  And while you're at it, what system are you using and which version of asciimatics are your running?

**Comment by tonybaloney** [comment]
hey @peterbrittain no it doesn't make any sense, it is definitely a str I put a breakpoint in there to check it.

The weird thing is the app loads fine, then after a bit it bombs out. It's after I've made some changes to the UI and called .refresh()
Its Mac OS on iTerm 2. My terminal is xterm-256, 

I think the TypeError message is a decoy, it's a shame you can't set the `errors` property of the stream object so it would at least not write whatever is causing the issue

**Comment by peterbrittain** [comment]
OK, so it's something that's happening during execution...  What is your application doing just before it blows out with the Exception?

**Comment by peterbrittain** [comment]
My best guess right now is that it's something about what you just set in the UI is somehow corrupting the stdout data stream and causing some confusion...

**Comment by tonybaloney** [comment]
I modified the `_safe_write` method to give me a bit more detail about what is going on, 
```python
        @staticmethod
        def _safe_write(msg):
            """
            Safe write to screen - catches IOErrors on screen resize.

            :param msg: The message to write to the screen.
            """
            try:
                sys.stdout.write(msg)
                global _last_value
                _last_value = msg
            except IOError:
                # Screen resize can throw IOErrors.  These can be safely
                # ignored as the screen will be shortly reset anyway.
                pass
            except TypeError:
                from retox.log import retox_log
                retox_log.error("Tried to write %s with value %s and crashed" % (type(msg), str(msg)))
                retox_log.error("The last value was %s" % (_last_value))
```
Amusingly, it is of type `str`, which is a bug in the standard lib. But The value's themselves I don't recognise. Also, it was probably the previous value, not this one that caused the issue. So whichever character that is (looks like the bottom right corner border?)

```
Tried to write <class 'str'> with value (B[m and crashed
The last value was ┘
```

**Comment by tonybaloney** [comment]
I actually think this is unrelated to asciimatics now. Thanks for your help. It's running a process in Tox and they have an open bug on this. But hopefully the code snippet helps someone else out ^^

**Comment by peterbrittain** [comment]
@tonybaloney Yeah - I can't see anything obviously wrong in asciimatics here.  That first string is just the terminal escape code to reset colours back to the default as defined in terminfo by `sgr0=\E(B\E[m`.  And as you say, the previous one is just a corner from a box.  Should all be fine.  

Looking at your original stack trace again, there is something very strange going on.  If you look at the code here: https://github.com/python/cpython/blob/230ffeae0a3961b1769806bd722c26227c84e8da/Lib/codecs.py#L376-L377

You can see that it appears to have recursed in some way.  Maybe the issue is that tox has somehow played around with the stdout stream in some way that it has encapsulated the actual stream in 2 StreamWriters and so the second one can never work (as it has been passed a byte string instead of the unicode).

**Comment by tonybaloney** [comment]
@peterbrittain ^^ this should help.

Somewhere in the clear() or change_colours methods, the colors are being set to a binary value

**Comment by peterbrittain** [comment]
Not sure you've caught it yet...  Looking at https://github.com/python/cpython/blob/3.6/Lib/codecs.py#L376-L377, I see that you've asserted that the stdout file has been passed a string, but I don't think that's right.  The string has just been encoded  by the StreamWriter atline 376...  which is what needs to happen in order to print to a terminal which supports utf-8 (for example) rather than Python strings.

**Comment by tonybaloney** [comment]
stdout is a buffered stream so it will encode that on either buffer full or flush. 
In the app, I’m getting all of the values passed to the stream as Python 3 string types but in this one scenario (which is where the app crashes without the assertion) it crashes when I refresh the screen. Asciimatics curses class will call a buffer flush on clear so you then see the bad value raising the encode error. 
There shouldn’t be any occurrences of a bytes type being written to stdout. 
Maybe it’ll be easier to make a simple app with that raises the issue. It seems to be there the colour changes when I refresh the screen

**Comment by peterbrittain** [comment]
Yup - a simple app to demo the problem would really help here.

**Comment by tonybaloney** [comment]
Just a thought but if https://github.com/peterbrittain/asciimatics/blob/master/asciimatics/screen.py#L2222 the value passed were mutable, then encoded to a bytes type it would change the value stored in the class.

In other calls to _safe_write you have created a new immutable value by calling .decode, this is one of the only places where that pattern isn't reused.

**Comment by peterbrittain** [comment]
Yeah - that could happen, but would be a rather naughty side effect for a stream write operation...  Does your program do anything to insert itself into the stdout stream (outside of the test you just created)?

**Comment by tonybaloney** [comment]
Aha! I think I've got it then. Because the app is spawning Tox processes, one of those processes must be writing to the stream. But only in certain scenarios. 

This is such an awful bug to squash!

**Comment by peterbrittain** [comment]
Yeah - it's doing its best to scuttle away and hide!

**Comment by peterbrittain** [comment]
I'm getting suspicious of this change in tox: https://bitbucket.org/hpk42/tox/pull-requests/115/fixed-console-encoding-issue/diff
I reckon that could easily cause the bug we're seeing with the strangely nested writers...

**Comment by peterbrittain** [comment]
Yup - this is the issue!  The following code works while the line to change sys.stdout is commented out, but breaks with the TypeError when not.

```
from __future__ import division
from asciimatics.effects import Cycle, Stars
from asciimatics.renderers import FigletText
from asciimatics.scene import Scene
from asciimatics.screen import Screen
import codecs
import sys

def demo(screen):
    effects = [
        Cycle(
            screen,
            FigletText("ASCIIMATICS", font='big'),
            screen.height // 2 - 8),
        Cycle(
            screen,
            FigletText("ROCKS!", font='big'),
            screen.height // 2 + 3),
        Stars(screen, (screen.width + screen.height) // 2)
    ]
    screen.play([Scene(effects, 500)])

old_stdout = sys.stdout
# sys.stdout = codecs.getwriter('utf8')(sys.stdout)
Screen.wrapper(demo)
sys.stdout = old_stdout
```

Exactly the same problem is hit if you just use `print()` instead of the asciimatics Screen, so this is really a bug in tox IMHO.

**Comment by peterbrittain** [comment]
Note that the problem is that tox is setting up UTF-8 StreamWriter around a UTF-8 TextIOWrapper.  Getting access to the underlying BufferedWriter instead would fix the issue.   For example:

    sys.stdout = codecs.getwriter('utf8')(sys.stdout.buffer)
