### ISSUE TITLE
Non-unicode version? Wcwidth is a resource hog.

### ISSUE THREAD

**Issue by scottmudge** [peterbrittain/asciimatics#155]
I understand the need for uni-code characters in modern applications, but for some which only need the standard ascii characters, calling Wcwidth repeatedly is needlessly eating up a ton of resources:

![image](https://user-images.githubusercontent.com/19617165/39925781-fdbaaebe-54fa-11e8-8d5b-b309dd9bcce3.png)

In this particular application, it alone is taking up 57% of total application CPU time. 

It would be nice if there were a way to tell asciimatics to use len() instead. I'm going to create a fork and modify the code to allow for this switch and post the results.

**Comment by peterbrittain** [comment]
I'd be interested in what your application is doing if you're happy to share...  

When I first introduced unicode support, I spent a fair bit of time optimizing the logic so that all the samples still ran smoothly on my machine.  By the end I found that the cumulative time spent in wcwidth was between 5% and 20% of the application's CPU.  

None of the ones I tried hit your numbers, so if you can share a bit more, I'd be happy to look into ways to reduce the impact.

**Comment by scottmudge** [comment]
Hi Peter,

I'm writing an algorithmic trading application. For it I created a custom log viewer widget that takes up the bottom 35% of my screen, so that I can keep an eye on my Logger calls. I initially considered using a StringIO object in the log view widget, and then pass that to the Logger instance and bind it to a StreamHandler, but instead I opted for a simple callback and custom formatter:

![image](https://user-images.githubusercontent.com/19617165/39928359-27a50802-5503-11e8-88a1-528de7467669.png)

I could not use reduce_cpu=True with the log view widget in the Frame, as the logger gets updated quite frequently. And so the wcwidth/wcswidth functions were being called constantly.

But I added the option to use len() or other simpler logic under the assumption all characters are 1-character wide by adding 

`asciimatics.screen.set_unicode_support()`

Which simply sets a global boolean flag. Not sure if that's the right namespace or not, but it made sense to me.

But it fixed the CPU use problem:

![image](https://user-images.githubusercontent.com/19617165/39928570-b92d4b90-5503-11e8-8e83-0e8774c5941a.png)

You can look at my fork if you wish to add the ability to disable unicode/wide-character support or not. I find it useful, but you may wish to force wider compatibility, which is totally fine. I just didn't need wide characters.

Thanks!

**Comment by scottmudge** [comment]
Also, I've encountered an issue where my keyboard/mouse input will no longer be responsive until I raise a ResizeScreenError to trigger resetting the wrapper.

Is there a way to "soft-reset" the input? I have attempted to forcibly set the focus to a specific widget, but it does not work.

Thanks!

**Comment by peterbrittain** [comment]
OK - I think that there is any easy win here and then a harder one...  

- The easy one is just to use the `unicode_aware` flag that is already on the `Screen` to remove the call to `wcidth()`.
- The harder one is to use the same flag on the canvas to pass that through to the rest of the widget processing.

Making just the first change removes nearly all wcwidth usage in my samples and so I think is all that is probably all that is required here.  Now pushed to master - see https://github.com/peterbrittain/asciimatics/commit/68744d9c5184c1a751c2dd5ed973642c4ef59b73.

Also, you might consider using `force_update()` in your callback processing and then making your Log wait forever as its default refresh period.  This should reduce any unecessary redrawing when there are no updates.

**Comment by scottmudge** [comment]
Hi Peter,

Alright so I adapted my changes to use the unicode_aware flag already present in Screen, and had it pushed down using the frame._canvas object.

I'll create a pull request, as it really does improve performance for non-unicode applications. 

I'll look into adapting my log viewer widget to force updates following callbacks as well.

Thanks for the input!

**Comment by peterbrittain** [comment]
Pull request now merged.  Thanks.

**Comment by jquast** [comment]
We have made enourmous improvements to wcwidth performance since 0.2.14 and earlier when this issue was created, and today with 0.5.0 release.

Here is some automatic benchmarking results  from a downstream dependency, https://github.com/jquast/blessed/pull/344#issuecomment-3786814877 and I think this only represents the last 4 years, many more improvements were made since 2018.

### Performance Changes

|     | Benchmark | `BASE` | `HEAD` | Efficiency |
| --- | --------- | ------ | ------ | ---------- |
| ⚡ | [`` test_center_ascii ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_center_ascii&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 104.8 µs | 62.1 µs | +68.87% |
| ⚡ | [`` test_rjust_cjk ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_rjust_cjk&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 760.6 µs | 640.2 µs | +18.81% |
| ⚡ | [`` test_center_cjk ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_center_cjk&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 763.5 µs | 642.6 µs | +18.81% |
| ⚡ | [`` test_truncate_ascii ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_truncate_ascii&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 33,519.5 µs | 83 µs | ×400 |
| ⚡ | [`` test_center_ansi ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_center_ansi&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 678.1 µs | 359.2 µs | +88.78% |
| ⚡ | [`` test_truncate_cjk ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_truncate_cjk&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 14.2 ms | 6.8 ms | ×2.1 |
| ⚡ | [`` test_length_cjk ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_length_cjk&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 749.7 µs | 633 µs | +18.45% |
| ⚡ | [`` test_truncate_emoji_zwj ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_truncate_emoji_zwj&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 5.2 ms | 1.6 ms | ×3.4 |
| ⚡ | [`` test_rjust_ansi ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_rjust_ansi&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 673.7 µs | 356.1 µs | +89.19% |
| ⚡ | [`` test_truncate_ansi ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_truncate_ansi&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 46.1 ms | 23.2 ms | +99.18% |
| ⚡ | [`` test_length_ansi ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_length_ansi&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 672.2 µs | 488.9 µs | +37.5% |
| ⚡ | [`` test_length_ascii ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_length_ascii&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 99.2 µs | 60.4 µs | +64.23% |
| ⚡ | [`` test_rjust_ascii ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_rjust_ascii&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 99.8 µs | 58.9 µs | +69.33% |
| ⚡ | [`` test_ljust_ansi ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_ljust_ansi&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 670.5 µs | 355.3 µs | +88.74% |
| ⚡ | [`` test_ljust_ascii ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_ljust_ascii&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 100.2 µs | 58.9 µs | +70.1% |
| ⚡ | [`` test_ljust_cjk ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_ljust_cjk&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 759.6 µs | 640.7 µs | +18.55% |
| ⚡ | [`` test_length_emoji_vs16 ``](https://codspeed.io/jquast/blessed/branches/jq%2Fwcwidth-0.3.0?uri=tests%2Ftest_benchmarks.py%3A%3Atest_length_emoji_vs16&runnerMode=Simulation&utm_source=github&utm_medium=comment&utm_content=benchmark) | 739.7 µs | 670.7 µs | +10.28% |
