### ISSUE TITLE
Flickering screen

### ISSUE THREAD

**Issue by matcool** [peterbrittain/asciimatics#179]
My current code
```python
def main(screen):
    while True:
       screen.clear()
       #do drawing
       screen.refresh()
Screen.wrapper(main)
```
It keeps flickering because when it clears the screen it also updates the command line so for a frame you see a blank screen and on the next one you see the thing you have drawn, but I need the clearing to remove stuff I don't want from the previous frame. Is there any advice for how to fix this?

**Comment by peterbrittain** [comment]
Yes -  I would expect something like that.  `Screen.clear()` is intended to be used at the start of day when you genuinely want to clear everything and reset back to a blank screen.

What you actually want to do is clear the double buffer that asccimatics is maintaing for you.  Then when you call refresh it willl clear out the bits that you haven't subsequently redrawn.  Try using something like this instead of calling `clear()`:

    for y in range(screen.height):
        screen.print_at(" " * screen.width, 0, y, colour, attr, bg)

Where colour, attr and bg are the various colours and attributes you want to use to clear the screen.

**Comment by peterbrittain** [comment]
I'm assuming this answered the question.  Let me know if not...
