### ISSUE TITLE
DatePicker and TimePicker widgets both assume an initial value

### ISSUE THREAD

**Issue by jvickroy** [peterbrittain/asciimatics#196]
DatePicker and TimePicker widgets both assume an initial value; otherwise, they raise
                AttributeError: 'NoneType' object has no attribute 'strftime'
in their respective update(self, frame_no) methods.

This can be demonstrated by commenting-out the "DATE" and "TIME" entries in the form_data dictionary of:
                ...\asciimatics-1.10.0\samples\forms.py

**Comment by peterbrittain** [comment]
Ok - I can see that would be frustrating in some cases.  I guess I can default to the date/time right now instead.

**Comment by peterbrittain** [comment]
Yeah - I thought about that, but when I coded it up I found that I wanted to read settings more easily using the data for the entire form rather than needing a reference to each object, so provided a symmetrical way to set it up to reduce the amount of code you'd have to write.

If you want to set a value more directly, you can always just set the value property directly on any of the Widgets.  I'm not sure how I feel about providing a third way to do it...  Will mull it over.

**Comment by peterbrittain** [comment]
Yeah - some better docs at the same time would help.  Will do that.
