### ISSUE TITLE
CustomColour does not work on all widgets

### ISSUE THREAD

**Issue by jabdoa2** [peterbrittain/asciimatics#208]
**Describe the bug**
CustomColour only works on certain widgets. For example Labels always use the "label" color.

**To Reproduce**
```
from asciimatics.scene import Scene
from time import sleep
from asciimatics.screen import Screen
from asciimatics.widgets import Frame, Layout, Label

screen = Screen.open()
frame = Frame(screen, screen.height, screen.width, has_border=False)
title_layout = Layout([1])
frame.add_layout(title_layout)
title_text = Label("MPF Framework v1.2.3", align="^")
title_layout.add_widget(title_text)
title_text.custom_colour = "title"
frame.fix()
scene = Scene([frame], -1)
screen.set_scenes([scene], start_scene=scene)
screen.draw_next_frame()
sleep(1)
screen.close()
```

**Expected behavior**
Label Text should use "title" color.

**Actual behavior**
Label Text uses "label" color.

**System details (please complete the following information):**
 - OS and version: Linux
 - Asciimatics version: 1.10.0

**Comment by peterbrittain** [comment]
Yeah - looks like some widgets still pick from the palette directly.  Should be an easy fix to use a suitable lookup function instead.

**Comment by peterbrittain** [comment]
Just looking at this one now...  It would appear that the only widget that totally fails to do this is the Label widget.  All the rest will use a hard-coded "label" colour if they also have a label and so the UI is consistent.

The basic scheme is as follows:

- The Frame (background, border, title, shadow, etc) all use hard-coded palettes that cannot be overridden.
- The ScrollBar (when it is used and enabled) also uses the relevant hard-coded palette entries.
- The Label widget (and all labels attached to Widgets) use the hard-coded "label" palette.
- All other Widgets can be overridden using the custom colour setting.

I am perfectly happy that the Frame and ScrollBars are out of the user's control - there are no settings to allow them to change this.  The only question is what to do about Labels, which straddle two worlds - being a Label widget in their own right and being a component of another Widget.

The simple fix (that I imagined before looking at this in more detail) was that we just fix up any rogue widgets to draw in the custom colour.  However, that then leaves the question of how to handle labels that are embedded within another widget (by setting the `label` property).

I could (a) ignore the issue and still have them drawn with a hard-coded "label" colour, or (b) refactor the packge to treat them as fully formed widgets in their own right.

The latter is more effort and so only something I want to do if you have an explicit need for it.  Your example only needs (a).  Can you please confirm that you don't also need (b)?

Your sample would be fixed by (a)

**Comment by jabdoa2** [comment]
I only need a current. Those are my current hacks: https://github.com/missionpinball/mpf/pull/1339/files
