### ISSUE TITLE
Label Pads Next Widget

### ISSUE THREAD

**Issue by peterjschroeder** [peterbrittain/asciimatics#215]
**Describe the bug**

When adding a label to a widget, the next widget also gets padded with that labels space.

**To Reproduce**
Steps to reproduce the behavior.  This could be some simple steps in the provided samples, or a minimum, complete verifiable example of your own.  See https://stackoverflow.com/help/mcve for details.

Add label to a widget, add a widget below it.

**Expected behavior**

No padding in other widget.

**Screenshots**
If applicable, add screenshots or cut and paste the erroneous text to help explain your problem.
![blah](https://user-images.githubusercontent.com/10292399/57202674-2d661680-6f76-11e9-9260-850273edbd02.jpg)

**System details (please complete the following information):**
 - OS and version: [e.g. Linux (Debian Sid)]
 - Asciimatics ersion [e.g. 1.9.0]

**Additional context**

**Comment by peterbrittain** [comment]
If I understand correctly, you're saying that you want to use the `label` property in one widget, but not in another and then want to mis-align the input fields for these widgets in your form.  And the screen shot shows that form with some magnifying glass as the label (where you want the list to align with the magnifying glass rather than the search text).  Is that right?

If so, this is going against the intended design for a single `Layout`..  This object is trying to create a consistent view for all the widgets it owns.  However, I realised that people won't always want everything to align like that and so asciimatics supports multiple Layouts in one `Frame`.  All you need to do is put the widgets that want a different alignment (i.e. the ones with no label) in a second `Layout` and it should just work as per your requirements.

**Comment by peterjschroeder** [comment]
That is correct. Thank you for the explanation. It makes sense for most widgets, but it looks odd for the ListBox. I went ahead with your suggestion for a second Layout and it works, thank you.
There is a second issue I am having shown in the same screenshot. There is a blue scrollbar showing over the frame, and I'm not sure why it is displaying. If I disable the frame, it goes away.

**Comment by peterbrittain** [comment]
That looks like it is the default scroll bar on the Frame.  You acn remove that by specifying `can_scroll=False` when constructing your Frame (as long as you are on a sufficiently new version of asciimatics.

In themeantime, it looks like I need to update the docs.

**Comment by peterjschroeder** [comment]
That worked. Thank you.

**Comment by peterbrittain** [comment]
Now documented this use case in latest docs in master.
