### ISSUE TITLE
Resetting value after setting options in ListBox

### ISSUE THREAD

**Issue by egakupi** [peterbrittain/asciimatics#227]
**Describe the bug**
In case of options updates, it is impossible to select any other than 0 value in ListBox.
Along with the [ListBox options setting](https://github.com/peterbrittain/asciimatics/blob/d26c9c4440072078b3f790b9217d5054fb2895f1/asciimatics/widgets.py#L2789) happens:
`self.value = self._options[0][1]`

**To Reproduce**
```
class CommonView(Frame):
    def __init__(self, screen):
        super(CommonView, self).__init__(
            screen,
            screen.height * 2 // 4,
            screen.width * 2 // 4,
            hover_focus=True,
            can_scroll=False,
            title='Title',
        )
        self._operations = [('Oper0', 0), ('Oper1', 1)]
        self._device_list = ListBox(
            Widget.FILL_FRAME,
            self._operations,
            add_scroll_bar=True,
            on_select=self._select)
        layout = Layout([100], fill_frame=True)
        self.add_layout(layout)
        layout.add_widget(self._device_list)
        self.fix()

    @property
    def frame_update_count(self):
        return 20

    def _update(self, frame_no):
        super()._update(frame_no)
        self._device_list.options = get_updated_device_list()

    def _select(self):
    for path, i in self._device_list.options:
        if i == self._device_list.value:
            raise Exception(i, path)
```

**Expected behavior**
Correct selection of any item from the ListBox

**Actual behavior**
After selection any item, [the value](https://github.com/peterbrittain/asciimatics/blob/d26c9c4440072078b3f790b9217d5054fb2895f1/asciimatics/widgets.py#L2474) is the value of the first item in ListBox.

**Details:**
 - Asciimatics 1.11.0

**Comment by peterbrittain** [comment]
Let my try to restate the problem.

The issue in your sample code is that it is replacing the options on every update.  This will (as you point out) reset the selected value to the first item in the options list.  You would like it so that when you change the list of options in a ListBox, asciimatics reinstates the current value.  

That's probably OK when your new set of options is actually the same as the old set, but what about when it changes?  I think the proposal for this change would be that it does a best effort to reinstate the old value.  If it can't find it, it will fall back to the current logic.

That should fix the sample shown here, but still do something sensible when you remove the selected value.

**Comment by egakupi** [comment]
Thank you for response so quickly.

In my project, I've temporarily removed the line:
`self.value = self._options[0][1] if len(self._options) > 0 else None`

I thought it was done for selection first item after updating. But the first item is selected after updating options without this line. Perhaps there is other reason of the "value line" but I didn't find.

**Comment by peterbrittain** [comment]
This class needs the options, line and value to be maintained in lockstep for the widget to work as expected.  IIRC, I added that initialization to prevent internal errors due to inconsistent state highlighted in some tests and would be slightly nervous that you may hit this on further testing.  

A better fix might be just to use `self.value = self._value`, which will force the widget to reevaluate the value and associated line with the new options list.

**Comment by egakupi** [comment]
Now I figured out what the line was for. Your fix sounds good.

**Comment by peterbrittain** [comment]
Easy fix - tested and has the desired effect on value.  Your code should now work with master branch.
