### ISSUE TITLE
Disable the cursor on the screen?

### ISSUE THREAD

**Issue by akennedy4155** [peterbrittain/asciimatics#231]
Is there a way to disable the cursor from showing up on the screen?  Right now it travels around in a weird way.  I've checked Widget.py, and Screen.py and searched around but it seems like there's no option to disable the cursor from showing up.  I'm a noob.  Any ideas?

**Comment by peterbrittain** [comment]
The cursor should be switched off, which is why asciimatics emulates its own in text widgets...  Sounds like you've hit a bug.  My best guess is that you're running on a curses system (*nix or Mac) and using a bad terminal definition.

Can you please give more details of your system - e.g. operating system, version of asciimatics, terminal/console you are using and (if it is *nix) the output of infocmp.

**Comment by akennedy4155** [comment]
Windows 10, VSCode terminal.  Should I try in a Git Bash or CMD maybe?  Also thanks for the response so late at night!  I'm impressed with how attentive you are to this project.  A true labor of love.  Love everything about the library so far!  Just learning the basics and trying to write my own Widgets for a Blackjack Game!

**Comment by akennedy4155** [comment]
UPDATE: ran in windows CMD and everything is working as planned.  Thanks for the info.  I should hav tried this first.

**Comment by peterbrittain** [comment]
Not that late where I am.

I'm surprised it ran at all inside vscode!  Most IDEs don't run enough of the console system to even start.
