### ISSUE TITLE
Encapsulating the scene in a statement (Press any key or press enter to continue)

### ISSUE THREAD

**Issue by ig0r777** [peterbrittain/asciimatics#243]
Sir,

Amazing module, I just love it. I am building a game for my son and I just found this. The game already works pretty well but I did a lot of the Ascii stuff with Pyfiglet and online Jpg to ascii converters, but asciimatics is just so much better at everything!! I am going to convert my entire game over to asciimatics. Thanks for your hard work. 

I am just starting to learn asciimatics and I was wondering how I can have a scene play and then return to my original code with a "Press enter to continue" or press any key to continue, or just have it play a time limit like 5 seconds or so.

Thanks,
Josh

**Comment by peterbrittain** [comment]
Thanks!  It's nice to know that I'm not the only one who finds this stuff fascinating.  :-)

To stop the `play()` loop at any time, you just need to raise a `StopApplication` exception.  The play loop will catch that exception and exit.  You can use this sort of code (https://github.com/peterbrittain/asciimatics/blob/660f2bf9578e78ea2c7bee0c73a3c5277e8afa5f/asciimatics/screen.py#L1502-L1511) to do this by passing it in as the `unhandled_input` parameter on `play()`.  Alternatively you could put that as custom logic in the event handling logic for a new Scene type that you create.  See the top.py demo for an example of how to do this.

In order to put a time limit on this sort of thing, simply pass `repeat=False` to `play()` and construct your Scene with a suitable `duration` - e.g. 100 for 5s.

**Comment by ig0r777** [comment]
So Scene.play(repeat=False, duration=100)

Something like this?

**Comment by peterbrittain** [comment]
Not quite...  

More like this: `screen.play([Scene(effects, duration=100)], repeat=False)`

**Comment by ig0r777** [comment]
Shame - I know my name!! haha. Thanks Peter!

**Comment by peterbrittain** [comment]
No problem.  If you have any other questions, feel free to ask them on gitter (check out link in the README) instead of raising new issues.
