### ISSUE TITLE
asciimatics and pexpect

### ISSUE THREAD

**Issue by egakupi** [peterbrittain/asciimatics#261]
**Describe the bug**
I have issue with asciimatics and pygatt. Pygatt is a wrapper for gatttool and it uses pexpect. Pexpect has some problems with curses app.
 
**To Reproduce**
To use asciimatics and pygatt together

**Additional context**
I found [ptyprocess](https://github.com/pexpect/ptyprocess). May be It can help, but it has no 1to1 interface with pexpect.

May there are another possible ways to solve the problem

Thanks!

**Comment by peterbrittain** [comment]
Not sure what you need here...  Full-screen applications (of the sort that asciimatics produces) use the underlying terminal control codes to format the screen.  This is a stateful API that doesn't interoperate seemlessly with the simple text I/O that your standard command line tools use.  

Fundamentally, both sides need to cooperate with each other (so that the full-screen application can embed the text at the right place in its output stream).  This is typically achieved with a pty, which the fullscreeen application opens to communicate with the command-line.  You can see an example of how to do this in the terminal.py sample.

Now, this pty interface is also what is used by pexpect to control the commands that it scripts.  Unfortunately, that means that pygatt is handling the output from gatttool instead of asciimatics.  If you can tell pygatt to pass the output on to your asciimatics application, you could then handle it whatever way you desire.

Alternatively, if you're trying to run asciimatics from another application that happens to be using pexpect, you will see all the control codes used to format the display(and so need to take that  into account when creating your expect regexps.

Either way, I don't think asciimatics can solve the problem for you, I'm afraid.

**Comment by peterbrittain** [comment]
One further thought...  Have you tried looking for other bluetooth packages (that don't use pexpect)?

**Comment by peterbrittain** [comment]
I'm assuming this has addressed this issue.  Please feel free to add more info if not...
