### ISSUE TITLE
Form won't update regularly, only on key event.

### ISSUE THREAD

**Issue by busyDuckman** [peterbrittain/asciimatics#269]
Hi, thanks for the great software :) 
I am not sure if this is supported, please forgive me if it should have been a feature request.

**Describe the bug**
I wanted to update a form with live data, refreshing regularly.  It's not working for me after trying a few things with threads, and reading the solutions to the old bug reports.

**To Reproduce**
I attached an example clock application showing  a simplified version of my use case. 
It only updates the time when a key is hit.
[clock_test.txt](https://github.com/peterbrittain/asciimatics/files/5230673/clock_test.txt)

**System details (please complete the following information):**
 - OS and version: Linux
 - Asciimatics version: 1.11.0

**Comment by peterbrittain** [comment]
No problem.  This is all working as designed and there is an easy fix...

The biggest drain on resources in asciimatics is the screen refresh, so in order to keep unnecessary processing to a minimum, it will only redraw when it thinks there is something to do.  It does this by querying each Effect to find out when it next wants to be redrawn.

In your sample application, the Effect is the Frame and it will look at all the Widgets and check when they need to be redrawn.  Since nothing is changing, it will decide that nothing needs to be done and so asciimatics will just sit idling until there is some input.

To fix this application, you just need to force the Frame to say it always needs refreshing in a timely manner, by adding code like this to `ClockFrame`:

```
    @property
    def frame_update_count(self):
        return 20
```

This will tell asciimatics to redraw every 20 frames - i.e. once a second.

If you're using a multi-threaded environment and want to force the main thread to redraw, you can do that with [`force_update`](https://asciimatics.readthedocs.io/en/stable/asciimatics.html#asciimatics.screen.Screen.force_update).

**Comment by busyDuckman** [comment]
Awesome, that fixed it.

I saw that in the top.py example, but did not realise asciimatics looked at it.
