### ISSUE TITLE
ENH: samples for common UI forms seems slow

### ISSUE THREAD

**Issue by norok2** [peterbrittain/asciimatics#32]
The examples in `forms.py` seems to be slow, e.g. typing in the input text was slightly bu perceavibly unresponsive

**Comment by peterbrittain** [comment]
Can you please give me some more background here...?  For example:

* What OS are you using?
* What CPU do you have?
* What version of asciimatics are you running?

In addition, is there any way you can quantify the slowness?  Does it tally with the screen refresh delay (which should be 0.05s), or is it more pronounced than this?

**Comment by norok2** [comment]
Ubuntu 14.04 / Intel Core i7 3770K / asciimatics 1.6.0

I think it is the background animation that causes the other portions of the window (and hence whatever one types) to be refreshed at the 0.05s rate that you are suggesting. Once I removed that, I could no longer perceive a delay between what I typed and what was displayed).

**Comment by peterbrittain** [comment]
Yeah - that animation is something that I'm working with for V1.7, so wouldn't normally be there.  That was what I was going to suggest next...

If you're running any other samples, you're probably best to stick to the last stable release - i.e. https://github.com/peterbrittain/asciimatics/tree/v1.6/samples - rather than my latest unstable versions on master.
