### ISSUE TITLE
asciimatics VS python-prompt-toolkit

### ISSUE THREAD

**Issue by hongyi-zhao** [peterbrittain/asciimatics#325]
I want to reimplement the [percol](https://github.com/mooz/percol) based project [ariadne](https://github.com/hongyi-zhao/ariadne). It seems that both [python-prompt-toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit) and [asciimatics](https://github.com/peterbrittain/asciimatics) are reasonable candidates, but the former looks like more powerful and popular. Experience in using and comparing the two tools would be greatly appreciated.

Regards,
HY

**Comment by peterbrittain** [comment]
PPT has been around for a very long time and is great for REPL applications.  It hasn't been as strong on full screen applications, though, which is why the community advice for years was to use urwid for that case.  Personally, I didn't like the APIs they provided, so wrote asciimatics.  YMMV.

**Comment by hongyi-zhao** [comment]
So, the more suitable for my case is [urwid](https://github.com/urwid/urwid) or [asciimatics](https://github.com/peterbrittain/asciimatics). And it seems that urwid has a longer history and more feature set than asciimatics. Am I right?

**Comment by peterbrittain** [comment]
Just because it has been around longer doesn't mean it's better (think google vs yahoo)...  

Obviously, I am biased as the author of asciimatics, but I would use it for any full screen application.  :-)  To give you some idea of asciimatics' flexibility, look at the examples:

- Standard forms entry - https://github.com/peterbrittain/asciimatics/blob/master/samples/forms.py
- Python implementation of top - https://github.com/peterbrittain/asciimatics/blob/master/samples/top.py
- Open streetmap viewer - https://github.com/peterbrittain/asciimatics/blob/master/samples/maps.py
- Terminal screen recording player - https://github.com/peterbrittain/asciimatics/blob/master/samples/player.py
- Ray casting game - https://github.com/peterbrittain/asciimatics/blob/master/samples/ray_casting.py

I think you'd struggle to cover that range in urwid.

**Comment by hongyi-zhao** [comment]
> Obviously, I am biased as the author of asciimatics, but I would use it for any full screen application.

By saying full screen application, do you mean it can only work with full screen mode? IMO, most TUI libraries support the resizing function of the terminal window.

> I think you'd struggle to cover that range in urwid.

Thank you for show me the power of asciimatics. The most wanted things for my case include but not limited to the following:

- Curses based operation with arbitrary shortkey binding.
- Incremental regex/string filtering.
- Real-time interaction with back-end data sets, which may be stored in json/sqlite or some other formats.
- Extract the result data set flexibly, e.g., specific field or the whole entry, and supply the user appropriate options to work with the selected data, say, executing the data as command, or `cd` to the target location by treating it as path, and so on.

**Comment by peterbrittain** [comment]
Re: fullscreen.  By fullscreen, I mean an application taking full control of the terminal (like top and vim), rather than just the current line (i.e any standard CLI command like ls, grep, etc).  Asciimatics is built for such fullscreen applications and will handle resizes as needed (which you can check by running the examples).

Re your requirements:

- Asciimatics uses curses on platforms that support it and will handle various nasty cases (e.g. unicode input and output) for you out of the box.  No problems there.
- It's not obvious to me that a TUI framework should mandate _any_ interface to back-end data.  You should be able to use anything you like.  Check out the contact_list sample for an example of how to use a simple sqlite DB.
-  Filtering is possibly more interesting...  It's possible that this could be done by some Widgets, but it is not common.  I would normally expect that to be handled by your application (e.g. repopulating the contents of a Listbox base on a new filter of your underlying DB).
- The handling of resulting data is down to your application.  It sounds like you have complex requirements on how to parse a single line of text...  I doubt any TUI framework will do all of that for you out of the box.  I suspect you need to write your own logic to tokenize and act on the text accordingly.
- If you want to run a process based on what the user has selected, use the standard Python methods for running it.  You can simply find what was selected by looking at the `value` of the relevant widget (or the `data` on the associated Frame).

Hope that helps!

**Comment by hongyi-zhao** [comment]
> Asciimatics is built for such fullscreen applications

Do you mean full control of the terminal (such as top and vim)?

>     * I would normally expect that to be handled by your application (e.g. repopulating the contents of a Listbox base on a new filter of your underlying DB).
>     * The handling of resulting data is down to your application.
>     * I suspect you need to write your own logic to tokenize and act on the text accordingly.

It seems that all your above comments mean the same thing: doing it with self-developed python code logic and interface it to the curses and TUI supplied by `asciimatics`.

See the following screenshot of [ariadne](https://github.com/hongyi-zhao/ariadne), which can give you a preliminary impression about the specific effect I want to achieve:

![image](https://user-images.githubusercontent.com/11155854/132219410-820a05d1-8b1d-4fc8-b2dc-d15c781936df.png)

**Comment by peterbrittain** [comment]
> Do you mean full control of the terminal (such as top and vim)?

Yes.

> It seems that all your above comments mean the same thing: doing it with self-developed python code logic and interface it to the curses and TUI supplied by asciimatics.

Yes.  TUI frameworks will provide you with ways to simplify common UI features, but don't typically provide integration with other services (e.g. databases).

**Comment by peterbrittain** [comment]
Looking at percol, it is not just a TUI library; it is a custom coded curses application that provides contextual suggestions of what you might want to type based on what you've already entered.  Whichever framework you pick, you will have to extract all the curses code, then integrate the remaining program logic (to build suitable suggestions and act on your selected option) with the framework of your choice.

Some frameworks have autocompletion features, which might give you a leg up, but I doubt they support the types of search percol supports.  I'm afraid that Asciimatics can only give you a very basic version with the DropdownList right now.  It will need several enhancements to provide a systemic suggestion system.

**Comment by hongyi-zhao** [comment]
Based on your above comment, there seems to be no other python library that suits me better than `percol`.

**Comment by peterbrittain** [comment]
Sadly.  Yes.  Anything else will require significant reworking of your existing code.

At thi point, I think we can close this issue...
