### ISSUE TITLE
Missing PEP8 suggested `__version__` variable

### ISSUE THREAD

**Issue by norok2** [peterbrittain/asciimatics#34]
As per title, the PEP8 suggested way of determining the version of your package within Python, i.e. by setting the `__version__` variable in the package namespace, is not present. Since you seems to be relatively diligent with the git tagging, I would suggest you looking into the `setuptools_scm` package.
If you want, I can submit a patch with a solution similar to what I normally use in my projects (see e.g. https://bitbucket.org/norok2/hdu ), where I basically let setuptools_scm automagically determine the version from git tags, unless I set it manually for some reasons in `setup.py` and then update the corresponding `__version__` variable in a previously specified file, usually `__init__.py`.

**Comment by peterbrittain** [comment]
Interesting...  I'll take a closer look...

**Comment by peterbrittain** [comment]
Just had a play and...  

**Pros**
* It's one of the options in the [Python Packaging User Guide](https://packaging.python.org/single_source_version/?highlight=single), so is standard practice.
* It's cleaner than my current implementation.

**Cons**
* Looks like I have to set up tags for each build in addition to my current branching strategy.
* Not clear what happens if it's invoked during/post install.

Further digging required...  I'll have to try a dummy install.  If that all looks clean and works as expected, I'll update to this mechanism.

**Comment by peterbrittain** [comment]
Some issues with versions when no setuptools_scm already installed locally and when running direct from GIT repo.  Looks like these now work (for me at least!).  Closing as implemented.
