### ISSUE TITLE
Cursor position?

### ISSUE THREAD

**Issue by imdaveho** [peterbrittain/asciimatics#36]
The README says the library can get cursor position, but nothing in the docs or example explicitly shows where I can get it. 

If not the position of the cursor, at least the x, y position of the latest output printed to the screen. Thanks.

**Comment by peterbrittain** [comment]
The README actually states that it supports "cursor positioning", by which I mean you can position the cursor at any point on the screen (in order to print something at a specific location).

Given that asciimatics:

* hides the actual terminal cursor (as it ruins any animations)
* does all input with no echo (so that you can control whether there is any output at all)
* handles all the messy interactions for you to get your output to the desired location
* optimizes any screen output on every refresh (so the cursor is almost certainly not where you think it is)...

Why do you need to __read__ the cursor position at all?

**Comment by imdaveho** [comment]
Hey Peter,

Re-read the README right after posting; and, yeah...face palm moment.

I'm actually using the lib to create a more interactive cli tool that's in
between your typical cli and a TUI. I'm looking to port/fork
python-inquirer to use asciimatics instead of blessings to render these
prompts for cross platform consistency.

Cursor positioning would have been nice just to handle where to print the
next set of questions/choices, but I can imagine building that into my
tool-- just thought there was a method that did that already.

You might be wondering why use asciimatics for this? Like you, I quickly
realized that there were not any frameworks/libraries that handle console
output consistently between linux/mac/windows. I've tried used
python-prompt-toolkit, but found it to be difficult to reason about, esp.
for my use case.

Thanks for the quick reply, you can close this ticket.

**Comment by peterbrittain** [comment]
Thanks for the vote of confidence in this project!  I'm glad I could help...
