### ISSUE TITLE
Form data resets when hitting enter while selecting Text, Radio widget when only one effect present

### ISSUE THREAD

**Issue by brycepg** [peterbrittain/asciimatics#44]
I've noticed unexpected behaviour while writing a program that uses asciimatics. This behavior can be reproduced easily enough using `samples/forms.py`. 

If you comment out all the effects except for `DemoFrame` so that it `effects` is equal to

    effects = [
        #Julia(screen),
        #ClockFrame(screen, 0, 0),
        #ClockFrame(screen, screen.width - 26, 0),
        #ClockFrame(screen, 0, screen.height - 13),
        #ClockFrame(screen, screen.width - 26, screen.height - 13),
        DemoFrame(screen),
    ]

And then run file.
If you hit enter on a Text or Radio widget, it will reset all the form data, which is just about the only thing I'm not expecting enter to do.

This does not reproduce when there is another effect in addition to the `Frame` object. So right now I just have one `Clock` widget hidden behind my form to stop this. :)

The data resets itself even if I remove the `Reset` button, method as well.

This applies to me on asciimatics 1.5.0 and latest git as well as python 2.7 and 3.

Thanks Peter, for your work.

**Comment by peterbrittain** [comment]
Thanks for your support!

I think I see the issue here...  The widgets you're hitting this on don't actually handle the input and so it bubbles all the way up to the unhandled input function, which will move on to the next scene on Enter.  This resets the form for this demo.

I'll have a think about the proper fix, but in the meantime, you can just specify your own function (which could ignore all events) by passing it to `play()` as the `unhandled_input` parameter.

**Comment by brycepg** [comment]
passing an empty function to `screen.play(...,unhandled_input=lambda x: None)` Did fix it, thanks.

If I subclassed `Text` or `RadioButtons`, and extended the `process_event` method to do something with key codes `[10, 13]` (and not return the event in that case), then the events would not bubble up from `Widget` to `Effect` to `Scene` into the `Screen`, correct?

**Comment by peterbrittain** [comment]
OK - I've had a go at fixing it with https://github.com/peterbrittain/asciimatics/commit/2b4c9e6ed2c1e54d1d5d2ec8845656b4476d61fd.  That solves all the issues for me.  

Please let me know if that fixes it for you too, then I'll close the issue.

**Comment by brycepg** [comment]
That's an interesting way fix it. Yes the current master commit no longer has this issue, thanks.

**Comment by peterbrittain** [comment]
Great! I prefer to get asciimatics to give sensible defaults so that the user of the API doesn't have to get involved with the complexity if they don't want to...  It sometimes means I have to jump through a few hoops.

In this case, I would have has a circular dependency between the screen.py and widgets.py if I had just started looking an object types, so thought it best to expose the decision through a formal API.
