### ISSUE TITLE
Using _256_palette to print in 256 colors?

### ISSUE THREAD

**Issue by dho825** [peterbrittain/asciimatics#45]
How can this be achieved without using Rainbow or FigletText and only using screen.paint or screen.print with color maps?

**Comment by peterbrittain** [comment]
Assuming you are running a terminal that is capable of handling 256 colours, you just use the indices for the colour you want from the palette.  For example, if you want a pale yellow use 229.  You can find the complete colour scheme here: https://en.m.wikipedia.org/wiki/File:Xterm_256color_chart.svg.

If you're having problems getting 256 colours, have a look at the troubleshooting guide on this subject.

**Comment by imdaveho** [comment]
Oh whaat? that was easy...I was trying to call _256_palette directly but that was just a list of rgb at each step and didn't know how to combine them.

Probably due to my own lack of understanding with printing in 256 colors. Probably will dive deeper into how you're rendering it from the 256 palette, but any good resources to understand colors in terminal? I've basically ported over [this project](https://github.com/magmax/python-inquirer) using asciimatics, just need to add some finishing touches

**Comment by peterbrittain** [comment]
@imdaveho The palette is only used for image to text conversion, using PIL.  That's why it's this format - it's the one used by PIL.

As for general guides to terminals?  You might want to look at xterm and see how it works.  The [FAQ](http://invisible-island.net/xterm/xterm.faq.html) might be a good start.  But if you just want to know about colours, see [here](http://unix.stackexchange.com/questions/269077/tput-setaf-color-table-how-to-determine-color-codes).

**Comment by peterbrittain** [comment]
@dho825 Did that answer your question too?

**Comment by imdaveho** [comment]
Thanks Peter, you can close this ticket :)
