### ISSUE TITLE
Seems to  have additional requirement

### ISSUE THREAD

**Issue by pwillard** [peterbrittain/asciimatics#48]
has a win32console (part of PyWIn32) dependency.

**Comment by peterbrittain** [comment]
Thanks for getting in touch...  Can you plese clarify the issue?  

In particular, how did you install asciimatics?  If you installed with pip, it should handle this by installing pypiwin32.  Otherwise, did you follow the instructions in https://github.com/peterbrittain/asciimatics/blob/master/README.rst:

> If you don't use pip or it fails to install them, you can install the dependencies directly using the packages listed in requirements.txt. Additionally, Windows users will need to install pypiwin32.

**Comment by pwillard** [comment]
I used pip.  But when I try the sample code it says the pypiwin32 was not
installed. (Oddness)

I'm going to give the whole install another attempt

**Comment by peterbrittain** [comment]
I have had some issues with pip dependencies in the past because pypiwin32 can only install on Windows and that mechanism is fragile.  Looks like it's broken again.  Sigh.

Obviously, the workaround is just to pip install pypiwin32 too, but that's rubbish to force users to figure that out for themselves.  

I'll have a look at how it's gone wrong this time and see if [this solution](http://stackoverflow.com/questions/16055403/setuptools-platform-specific-dependencies/32955538#32955538) finally fixes it.

**Comment by peterbrittain** [comment]
Fixed by v1.7.2 release.
