### ISSUE TITLE
Backspace broken

### ISSUE THREAD

**Issue by boxed** [peterbrittain/asciimatics#53]
I'm getting key code 127 for backspace which is not handled properly. 

OSX Elcap.

**Comment by peterbrittain** [comment]
Thanks for getting in touch.  Sadly, I don't have easy access to OSX, so can't verify...

I suspect that this issue is because of your terminal definitions.  See http://www.ibb.net/~anne/keyboard.html for a good explanation of how the terminal can be messed up.  If that is the issue, please let me know so that I can fix up the troubleshooting guide.

**Comment by boxed** [comment]
Yea, seems like it. I forgot to mention that it's over an SSH tunnel I get this. Running locally on the remote machine works fine. But maybe asciimatics should handle this anyway? I mean, 127 isn't a valid key code for anything else is it?

**Comment by peterbrittain** [comment]
The problem is that 127 is actually the ascii code for the delete key and not the backspace key.  By treating it as backspace, I will break some other terminal out there...

I think we mighte be able to fix it by sorting out your terminal settings for your SSH client.  What client are you using, what terminal emulation is it using and what terminal type is it advertising itself as?

**Comment by boxed** [comment]
Ah. Well then close this ticket then. I'll look into my terminal on my own. Thanks.

**Comment by peterbrittain** [comment]
OK.  I'll add something to the troubleshooting section in my docs first.  If you find out anything that might be helpful for other users, please let me know.

**Comment by peterbrittain** [comment]
Now added.
