### ISSUE TITLE
Fix OS X char delete in Text widget

### ISSUE THREAD

**Issue by Imelstorm** [peterbrittain/asciimatics#93]
Fix OS X char delete in Text widget. For 1.8 version it's broken.

**Comment by peterbrittain** [comment]
I'm afraid that I don't really understand the issue that you're raising.  I think that you're saying that the "delete" key doesn't work in Text widgets on OSX.  

If so, please look at the trouble-shooting guidance here (http://www.ibb.net/~anne/keyboard.html).  If that doesn't help, can you please tell me:

- What terminal you are using
- What your terminfo definition is for your delete key
- What your terminal is configured to send for the delete key

**Comment by Imelstorm** [comment]
I'm trying say delete key in osx, doesn't erase characters inputed to Text widget. I'm using xterm-256color.

**Comment by peterbrittain** [comment]
That's always been down to terminal configuration issues so far...  Please try the trouble-shooting article in the above response.

**Comment by Imelstorm** [comment]
I'm will try trouble-shoot it, but maybe need reconsider it, because i'm using all default configs of term

**Comment by peterbrittain** [comment]
Thanks.  If I had to guess, I'd say that your definition for `kdch1` is wrong (based on articles like this one - http://hints.macworld.com/article.php?story=20050525040921189).  

If so, this is a bug in the terminfo database for OSX (and so nothing that I can change).

**Comment by Imelstorm** [comment]
I'm try say that this work properly in other application what I run in it, and only apps based on asciimatics doesnt work with this key. It's seems strange. So maybe need add handler for keycode of this key, which identify it?

**Comment by peterbrittain** [comment]
I'm sorry, but there is nothing I can do...

The problem is that this is not just as simple as a single key being misinterpreted by asciimatics.  What is actually going on is that you are running inside a Terminal emulator and so:

- The user presses a key.
- The Terminal application translates that keycode into the character sequence for the terminal that it is emulating (usually some variant of VT100).
- It passes this to the input stream, which is interpreted by ncurses using the terminfo database.
- Ncurses then tells asciimatics what key was pressed.

If the Terminal and ncurses disagree on the character sequence for a key, asciimatics will not be told that the user has pressed the key.  Depending on the sequence, it might be swallowed entirely, or you might just see the printable characters in the sequence, or it might even declare a completely different key was pressed.  It is wrong (and, in some cases, impossible) for asciimatics to fix this up.
